增加HttpProfile中对https请求是否进行严格验证的选项
TencentCloud/tencentcloud-sdk-php pull request #82
Opened 2020-11-03 16:41 UTC by LaoQi

暴露出GuzzleHttp库对ssl证书验证行为的选项，方便调试
https://docs.guzzlephp.org/en/stable/request-options.html#verify

```php
$cred = new Credential("secretId", "secretKey");
$httpProfile = new HttpProfile();
//$httpProfile->setVerify("path/to/cert");
$httpProfile->setVerify(false); // skip
$clientProfile = new ClientProfile(null, $httpProfile);
$client = new CvmClient($cred, "ap-guangzhou", $clientProfile);
```

2020-11-04 04:20 UTC, zqfan requested changes

2020-11-04 04:20 UTC, zqfan commented on src/TencentCloud/Common/Profile/HttpProfile.php
> +    private $verify;
构造函数里给一个初始值，默认应该是开启检查

2020-11-04 08:00 UTC, LaoQi commented on src/TencentCloud/Common/Profile/HttpProfile.php
> +    private $verify;
即使无初始值，默认是开启检查，不过严谨起见还是加入初始值吧。
文档给出的默认值为`GuzzleHttp\RequestOptions::VERIFY`
就是这个参数是否需要作为构造函数的输入参数之一？
```php
public function __construct($protocol = null, $endpoint = null, $reqMethod = null,  $reqTimeout = null, $verify = RequestOptions::VERIFY)
    {
        $this->reqMethod = $reqMethod ? $reqMethod : HttpProfile::$REQ_POST;
        $this->endpoint = $endpoint;
        $this->reqTimeout = $reqTimeout ? $reqTimeout : HttpProfile::$TM_MINUTE;
        $this->protocol = $protocol ? $protocol : HttpProfile::$REQ_HTTPS;
        $this->verify = $verify;
    }
```

2020-11-04 08:01 UTC, LaoQi commented on src/TencentCloud/Common/Profile/HttpProfile.php
> +    private $verify;
一般不会用到，感觉构造函数的参数列表太长了。

2020-11-05 03:02 UTC, zqfan commented
那等我验证下，在做决定把

2020-11-05 09:34 UTC, LaoQi commented
我先提交一份最少变更的上来吧，变更参数的这些后续再根据情况考虑
仅在构造函数赋值，其他没有变更。
```php
public function __construct($protocol = null, $endpoint = null, $reqMethod = null,  $reqTimeout = null)
    {
        $this->reqMethod = $reqMethod ? $reqMethod : HttpProfile::$REQ_POST;
        $this->endpoint = $endpoint;
        $this->reqTimeout = $reqTimeout ? $reqTimeout : HttpProfile::$TM_MINUTE;
        $this->protocol = $protocol ? $protocol : HttpProfile::$REQ_HTTPS;
        $this->verify = RequestOptions::VERIFY;
    }
```

2022-03-26 13:56 UTC, tianyiw2013 commented
为什么不合并呢？？？ @zqfan 
测试环境下php.ini不设置证书会报错：
```
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://tmt.tencentcloudapi.com/
```

希望尽可合并！谢谢。

2022-03-26 13:58 UTC, tianyiw2013 approved these changes
请尽早合并❤️

2022-03-26 14:30 UTC, tianyiw2013 commented
或者你们也可以直接提供CA根证书文件啊。
把`https://curl.haxx.se/ca/cacert.pem`直接放到你们源码里，`$this->verify = "cacert.pem";`
这样大家都不用担心这个问题。🤣

2025-09-01 03:58 UTC, closed without merging